site_name: WebGIS Starter

# Repository
repo_name: huanglii/webgis-starter
repo_url: https://github.com/huanglii/webgis-starter
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2023 huangli

theme:
  name: material
  language: zh
  logo: assets/logo.png
  favicon: assets/favicon.svg
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: 深色

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: 浅色
  font:
    text: Noto Sans SC
    code: Fira Code
  features:
    - content.action.edit
    # - content.action.view
    - content.code.copy
    - content.code.annotate
    # - content.code.select
    - content.tooltips

    - navigation.instant
    - navigation.tracking
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.path
    # - navigation.prune
    # - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer

    - search.highlight
    - search.share
    - search.suggest

    - toc.follow
    # - toc.integrate

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/huanglii
  # generator: false

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

# Page tree
nav:
  - 第 0 章 序: index.md
  - 第 1 章 概论:
      - chapter-introduction/index.md
      - 1.1 基本概念: chapter-introduction/concepts.md
      - 1.2 空间参考: chapter-introduction/spatial-reference.md
      - 1.3 GIS 软件: chapter-introduction/gis-software.md
  - 第 2 章 空间数据:
      - chapter-spatial-data/index.md
      - 2.1 矢量数据: chapter-spatial-data/vector.md
      - 2.2 栅格数据: chapter-spatial-data/raster.md
      - 2.3 开放数据: chapter-spatial-data/open-data.md
      - 2.4 数据处理: chapter-spatial-data/data-processing.md
  - 第 3 章 空间分析:
      - chapter-spatial-analysis/index.md
      - 3.1 空间插值: chapter-spatial-analysis/spatial-interpolation.md
      - 3.2 重采样: chapter-spatial-analysis/resampling.md
  - 第 4 章 地理可视化:
      - chapter-geographic-visualization/index.md
  - 第 5 章 空间数据库:
      - chapter-spatial-database/index.md
      - 5.1 PostGIS: chapter-spatial-database/postgis.md
  - 第 6 章 地图服务:
      - chapter-map-server/index.md
      - 6.1 GeoServer: chapter-map-server/geoserver.md
  - 第 7 章 前端框架:
      - chapter-frontend-framework/index.md
      - 7.1 Mapbox GL JS: chapter-frontend-framework/mapbox-gl-js.md
  - 第 8 章 附录:
      - chapter-appendix/index.md
  - 参考文献:
      - chapter-reference/index.md
